export const ACTION = {
    GET_CURRENT_COURSE: "GET_CURRENT_COURSE",
    //<<<<INTRODUCTION>>>>>
    SET_INTRODUCTION_HTML: "SET_INTRODUCTION_HTML",
    ADD_INTRODUCTION_SUCCESS: "ADD_INTRODUCTION_SUCCESS",
    GET_INTRODCUTION_HTML: "GET_INTRODUCTION_HTML",
    CLEAR_INTRODUCTION: "CLEAR_INTRODUCTION",
    //<<<BUILD_CIRCUIT>>>>>

    ADD_BUILD_CIRCUIT_SUCCESS: "ADD_BUILD_CIRCUIT_SUCCESS",
    GET_BUILD_CIRCUIT: "GET_BUILD_CIRCUIT",
    CLEAR_BUILD_CIRCUIT: "CLEAR_BUILD_CIRCUIT"
}