export const ACTION = {
    ADD_MODULE_SUCCESS: 'ADD_MODULE_SUCCESS',
    SET_MODULE_NAME: "SET_MODULE_NAME",
    SET_MODULE_INTRODUCTION: "SET_MODULE_INTRODUCTION",
    CLEAR_ADD_MODULE: "CLEAR_ADD_MODULE"
};