export const ACTION = {
    GET_MODULES: 'GET_MODULES',
    GET_CURRENT_MODULE: 'GET_CURRENT_MODULE',
    GET_COURSE_TROUBLESHOOT: 'GET_COURSE_TROUBLESHOOT',
    UPDATE_COURSE: 'UPDATE_COURSE',
    UPDATE_SUBMOD: 'UPDATE_SUBMOD',

};
