export const ACTION = {
    GET_CURRENT_COURSE: "GET_CURRENT_COURSE",
    //<<<<INTRODUCTION>>>>>
    SET_INTRODUCTION_HTML: "SET_INTRODUCTION_HTML",
    ADD_INTRODUCTION_SUCCESS: "ADD_INTRODUCTION_SUCCESS",
    GET_INTRODCUTION_HTML: "GET_INTRODUCTION_HTML",
    CLEAR_INTRODUCTION: "CLEAR_INTRODUCTION",
    //<<<BUILD_CIRCUIT>>>>>

    ADD_BUILD_CIRCUIT_SUCCESS: "ADD_BUILD_CIRCUIT_SUCCESS",
    GET_BUILD_CIRCUIT: "GET_BUILD_CIRCUIT",
    CLEAR_BUILD_CIRCUIT: "CLEAR_BUILD_CIRCUIT",

    //<<<EXPERIMENT>>>>>

    ADD_EXPERIMENT_SUCCESS: "ADD_EXPERIMENT_SUCCESS",
    GET_EXPERIMENT: "GET_EXPERIMENT",
    CLEAR_EXPERIMENT: "CLEAR_EXPERIMENT",

    //<<<EXPERIMENT_FORM>>>>>

    ADD_EXPERIMENT_FORM_SUCCESS: "ADD_EXPERIMENT_FORM_SUCCESS",

    //<<<EXPERIMENT_FORM>>>>>

    ADD_RESULTS_SUCCESS: "ADD_RESULTS_SUCCESS",


    //<<<TROUBLESHOOT>>>>>

    ADD_TROUBLESHOOT_SUCCESS: "ADD_TROUBLESHOOT_SUCCESS",
    GET_TROUBLESHOOT: "GET_TROUBLESHOOT",
    CLEAR_TROUBLESHOOT: "CLEAR_TROUBLESHOOT",

    //<<<EXCERCISE>>>>>

    ADD_EXCERCISE_SUCCESS: "ADD_EXCERCISE_SUCCESS",
    GET_EXCERCISE: "GET_EXCERCISE",
    CLEAR_EXCERCISE: "CLEAR_EXCERCISE"
}