export const ACTION = {
    ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
    SET_COURSE_NAME: "SET_COURSE_NAME",
    SET_COURSE_THUMBNAIL: "SET_COURSE_THUMBNAIL",
    CLEAR_ADD_COURSE: "CLEAR_ADD_COURSE"
};