export const ACTION = {
    GET_SOME_DATA: "GET_SOME_DATA",
    TOGGLE_SIDE: "TOGGLE_SIDE",
    CHANGE_CURRENT_STEP: "CHANGE_CURRENT_STEP",
    GET_CURRENT_COURSE: "GET_CURRENT_COURSE",
    GET_INTRODUCTION: "GET_INTRODUCTION",
    GET_BUILD_CIRCUIT: "GET_BUILD_CIRCUIT",
    GET_EXPERIMENT: "GET_EXPERIMENT",
    GET_RESULTS: "GET_RESULTS",
    GET_TROUBLESHOOT: "GET_TROUBLESHOOT",
    GET_EXCERCISE: "GET_EXCERCISE",
    GET_EXPERIMENT_FORM: "GET_EXPERIMENT_FORM",
    CHANGE_STEP: "CHANGE_STEP"
};
